version: "3"

services:
  python-consumer:
    build: .
    env-file: ./app/.env

  influxdb:
    image: influxdb:1.8.4-alpine
    ports:
      - "8086:8086"
    environment:
      - INFLUX_USERNAME="influxdb"
      - INFLUX_PASSWORD="foobar"
